kind: pipeline
type: docker
name: pr-pipeline

trigger:
  event:
    - pull_request

steps:
  - name: build
    image: node:20-alpine
    commands:
      - cd src/
      - npm install --global corepack@latest
      - corepack enable pnpm
      - pnpm install --frozen-lockfile
      - pnpm run build

---
kind: pipeline
type: docker
name: release-pipeline

trigger:
  event:
    - push
  branch:
    - release

steps:
  - name: fetch-tags
    image: docker:git
    commands:
      - git fetch --tags

  - name: build
    image: node:20-alpine
    commands:
      - cd src/
      - npm install --global corepack@latest
      - corepack enable pnpm
      - pnpm install --frozen-lockfile
      - pnpm run build

  - name: semantic-release
    image: node:22-alpine
    environment:
      GITHUB_TOKEN:
        from_secret: GITHUB_TOKEN
    commands:
      - apk add --no-cache git
      - npx semantic-release@25

---
kind: pipeline
type: docker
name: release-docker

trigger:
  event:
    - tag

steps:
  - name: build-image
    image: plugins/docker
    settings:
      repo: cerfe/alboarrd
      username:
        from_secret: dockerhub_username
      password:
        from_secret: dockerhub_password
      context: src
      dockerfile: src/Dockerfile.prod
      purge: true
      tags:
        - latest
        - ${DRONE_TAG##v} # v1.2.3 -> 1.2.3
      daemon_off: true
