kind: pipeline
type: docker
name: build

trigger:
  event:
    - pull_request

steps:
  - name: build-react
    image: node:20-alpine
    commands:
      - cd src/
      - npm install --global corepack@latest
      - corepack enable pnpm
      - pnpm install --frozen-lockfile
      - pnpm run build
